# Generated by Django 4.2.7 on 2023-11-20 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='exp_date',
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('MobilePhone', 'MobilePhone'), ('Tablet', 'Tablet'), ('SmartWatch', 'SmartWatch'), ('Laptop', 'Laptop')], default='MobilePhone', max_length=100),
        ),
    ]
